---
title: "Professional Background"
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

------------------------------------------------------------------------

### Academic Qualifications

+---------------------+---------------------------------------------------+
| **Degree:**         | Master of Science                                 |
|                     |                                                   |
| **Field:**          | Decision Science                                  |
|                     |                                                   |
| **Specialization:** | Structural Equation Modeling                      |
|                     |                                                   |
| **Year:**           | 31 March 2013 (Graduation Date)                   |
|                     |                                                   |
| **Institution:**    | Universiti Utara Malaysia (UUM)                   |
+---------------------+---------------------------------------------------+

+---------------------+---------------------------------------------------+
| **Degree:**         | Bachelor of Science                               |
|                     |                                                   |
| **Field:**          | Mathematics with Economics                        |
|                     |                                                   |
| **Specialization:** | Operations Research                               |
|                     |                                                   |
| **Year:**           | 18 December 1992                                  |
|                     |                                                   |
| **Institution:**    | University of Kentucky, KY, USA                   |
+---------------------+---------------------------------------------------+

------------------------------------------------------------------------

### Courses Taught

Essential Mathematics\
Business Mathematics\
Introduction to Statistics\
Statistics for Social Sciences and Business Statistical Methods\
Regression Analysis\
Introduction to Time Series Analysis\
Operations Research\
Spreadsheet Modeling and Decision Making\
Introduction to Statistics\
Operations Research\
Spreadsheet Modeling and Decision Making

------------------------------------------------------------------------

### Previous Employment

-   AIMST University, Sungai Petani, Kedah (2001 -- 2002)\
    *Lecturer (Mathematics - South Australian Matriculation)*

-   Texas Instruments Malaysia, Ulu Kelang, Selangor (2000 -- 2001)\
    *Manufacturing Executive (Assembly Department)*

-   SAL Group of Colleges, Kuala Lumpur (2000)\
    *Lecturer (Discrete Mathematics)*

-   Universiti Putra Malaysia, Kuala Terengganu, Terengganu (1997 -- 2000)\
    *Science Teacher (Mathematics)*

-   Universiti Putra Malaysia, Serdang, Selangor (1993 -1997)\
    *Tutor (Mathematics)*

-   MARA Science College, Kuala Lumpur (1993)\
    *Lecturer (A-Level Mathematics)*

-   MIDAS Institute of Technology, Seremban, Negeri Senbilan (1993)\
    *Lecturer (Physics and Calculus)*

------------------------------------------------------------------------

### Administrative Responsibilities

-   Manager, Memorandum of Understanding (MoU) Between UiTM and Ecological University of Bucharest (EUB) Romania (23 March 2021 - 22 March 2024)

-   Coordinator, Micro-Credential Program for Faculty of Computer and Mathematical Sciences, UiTM Kedah (1st October 2020 - 30th September 2022)

-   Chairman, Final Examination Vetting Panel for Faculty of Computer and Mathematical Sciences, UiTM Kedah Branch Campus (1st October 2020 - 30th September 2022)

-   Final Examination Vetting Panel for Faculty of Computer and Mathematical Sciences, UiTM Kedah Branch Campus (2015 - 2020)

-   UiTM Kedah Big Data Lab Coordinator (May 2018 - May 2020)

-   Internal Auditor Team UiTM Kedah Branch Campus (2005 - 2020)

-   Technical Committee Members on Computer Equipment Disposal for UiTM Kedah Campus (1st October 2006 - 14th November 2007)

-   Technical Committee Members on Computer Equipment Disposal (2009 - 2014)

-   Coordinator\
    1. Dept. of Information Technology & Quantitative Sciences (2006 - 2007)\
    2. Unit of Information Technology (2006 -- 2007)

------------------------------------------------------------------------

### Current Professional Membership

-   SEA Member -- The Romanian Foundation for Business Intelligence (September 1, 2016)

-   Persatuan Sains Matematik Malaysia (PERSAMA)

-   Institut Statistik Malaysia (ISM) - Members No: 156
