---
title: "Academic Activities"
output:
  html_document: 
    toc: false
    toc_float: false
---

<link rel="stylesheet" href="styles.css" type="text/css">

## {.tabset}

### <i class="fas fa-university"></i> Research
“Integrating English Medium Mathematics Mobile Applications To Teach Low Achievers Students In tertiary Context”, ARAS Research Grant. (September 1, 2016 – August 31, 2018)

“The Effect Of Gender And Religion on The Perceived Mental Health Among Youth in Kedah”, Dana Kecemerlangan UiTM. (November 1, 2015 – April 30, 2017)

“Factors Influencing Purchasing Intention of Smartphone Among University Students”, Dana Kecemerlangan UiTM. (November 1, 2015 – April 30, 2017)

“Factors That Contributes to the Intention to Adopt Websites as Marketing Communication Tool among SME’s in Kedah: A Business Perspective”, Internal Grant, August 2010

“The Study of Technophobia among Students in UiTM Kedah”, Internal Grant, May 2010

“The Effectiveness and Efficiency in the Usage of Software e-MySL© in Learning Malaysian Sign Language (MySL)”, Internal Grant, December 2008

“Impak Pembangunan Terhadap Tahap Pendidikan dan Pendapatan Orang Asli di Tanah Tinggi Cameron”, Internal Grant, April 2007

“A Survey on Factors Which Positively Influence Ethical Decision Making among Young Lawyers Practicing in the State of Kedah”, Internal Grant, January 2007

“Descriptive Analysis On The Use of ICT Among Faculties Offering Quantitative Sciences and Information Technology Courses in Northern Region IPTA”, Internal Grant, December 2006

“Student's Perception Of Service Quality: A Case Study in UiTM Kedah And Perlis Branch”, Internal Grant, May 2006

“Perpustakaan Masjid Di Negeri Kedah: Satu Tinjauan”, Internal Grant, December 2005

“Analisis Program Pembasmian Kemiskinan Dari Perspektif Penduduk Miskin Tegar di Kawasan Parlimen Merbok, Kedah”, Internal Grant, March 2005

### <i class="fas fa-globe-asia"></i> Conferences  
Kamarul Ariffin Mansor, Wan Irham Ishak, Shafinah Md Salleh, Ab Razak Mansor (2020). INTEGRATING ENGLISH MEDIUM MATHEMATICS MOBILE APPLICATIONS TO TEACH LOW ACHIEVER UNIVERSITY STUDENTS. The 5th National & the 2nd International Academic Conference “Roles of the university as the driver for changes and Innovation-based society, 13th – 14th February 2020 At Rattanathepsatri Building, Thepsatri Rajabhat University. Conference Proceedings, 92-102. [PDF](files/Full paper in conference PROCEEDINGS 2020 Roles of the university as the driver for changes and Innovation-based society.pdf)  

Bosli, F., Mokhtar, S. F., Shamsuddin, N. R., Zawawi, T. K. F. T. A., Mansor, K. A., & Salleh, W. Z. W. (2017). Factors Affecting the Tendency of Drug Abuse among Drug Addicts: A Case Study in the Northern Region of Malaysia. The 6th International Conference on Public Policy and Social Science (iCOPS2017), 8th & 9th March 2017, The Hotel & convention Centre, Alor Setar, Malaysia. ICOPS2017 eProceedings, 545. (ISBN 978-967-0314-41-9) [PDF](files/FULL-PAPER-ICOPSS2017.pdf)

“The Antecedents Buying Intention of New Smartphone among University Students” (with Azira Rahim, Dr. Law Kuan Kheng, Kamarul Ariffin Mansor and Nurliyana Abas), 2nd International Conference on Information in Business and Technology Management (I2BM), 18 - 20 April 2017, Penang, Malaysia.

Marzuki, Marzlin; Zakaria, Maheran; Ab Ghani, Nazri; Abdul Rasit, Zarinah; Mansor, Kamarul Ariffin (2015). A Study on Student's Learning Approaches and Preferences on Academic Performance. Asean Conference on Accounting Education (ACAE 2015). 30 October - 2 November 2015.  Sunway University, Selangor, Malaysia. [WEB](http://www.youblisher.com/p/1249891-A-Study-on-Students-Learning-Approaches-and-Preferences-on-Academic-Performance/)

“How Far Ethics Education Positively Influence Ethical Decision Making of The Young Lawyers in Kedah?” (with Haswira Nor Mohamad Hashim and Anida Mahmood, Proceedings of Conference on Scientific and Social Research (CSSR 08'09), 14 – 15 March 2009, A’Famosa Resort Melaka.

“The Effectiveness and Efficiency in the Usage of Software e-MySL© in Learning Malaysian Sign Language (MySL)” (with Haziah Sa’ari, Marlia Idrus and Mohd Shamsul Daud), Proceedings of Conference on Scientific and Social Research (CSSR 08'09), 14 – 15 March 2009, A’Famosa Resort Melaka.

“A Study on English Language Competency Perception Among Lecturers in Higher Learning Institution” (with Shafinah Md Salleh and Wan Irham Ishak), Proceeding of 1st International Conference on Social Science and Humanities 2008 (ICoSSH 2008), 18 – 20 June 2008, Universiti Sains Malaysia (USM) Penang. (Proceedings CD ISBN: 978-983-2700-65-4, Humanities HUM58 & Proceedings Abstract ISBN: 978-983-2700-69-2, pp 78)

“Impak Pembangunan Ke Atas Suku Semai Di Tanah Tinggi Cameron” (with Azizan Zainuddin, Mahadi Mahmood and Mohamad Sabri Yusoh), Proceedings of the National Seminar on Science, Technology & Social Sciences 2008, 3 – 4 June 2008, M.S. garden Hotel Kuantan Pahang. (Proceedings ISBN: 978-983-2607-17-5, pp 363 – 372)

“Factors Influencing Ethical Decision Making Among Young Lawyers: A survey in the State of Kedah” (with Haswira Nor Mohamad Hashim and Anida Mahmood), Proceedings of Law Conference 2007, 18 – 20 April 2007, EDC-UUM Sintok Kedah.

“Analisis Faktor Kejayaan dan Kegagalan Program Pembasmian Kemiskinan Dari Perspektif Penduduk Miskin Tegar Di Kawasan Parlimen Merbok, Kedah” (with Haswira Nor Mohamad Hashim, Muhammad Sazri Khamis and Zauyah Abd Razak), Proceedings of Conference On Scientific & Social Research (CSSR), 18 – 20 April 2007, Summit Hotel, subang Jaya Selangor.

“Analisis Tahap Pengetahuan Penduduk Terhadap Program Pembasmian Kemiskinan Tegar Di Kawasan Parlimen Merbok, Kedah” (with Haswira Nor Mohamad Hashim, Muhammad Sazri Khamis and Zauyah Abd Razak), Colloquium Paper presented in UiTM Kedah Colloquium 2005, 26 May 2005, Sg Petani Kedah.

### <i class="fas fa-print"></i> Publications  
NRNA Rashid, C Wangbenmad, KA Mansor (2020). Halal Tourism: Lessons for Destination Managers of Non-Muslim Majority Countries. International Journal of Business and Society, Vol. 21 No. 1, 473-490. Indexing: Scopus. [PDF](files/P28.pdf) 

Kalantan, Z.I., Alrewely, F., & Mansor, K.A. (2019). Study on the Convergence
Behavior of Expectation Maximization Algorithm for Laplace Mixture Model. Romanian Statistical Review, 3(2019), 35-45. Indexing: [ECSI Thompson Reuters and BDI](http://www.revistadestatistica.ro/index.php/indexing/) [PDF](files/A4_RRS-3_2019.pdf)  

Safin, Z., Ali, N.A., Jamalurus, H.L., Zani, R.M., & Mansor, K.A. (2018). Performance in Industrial Training: Industry Evaluation on Business and Management Students. Gading Journal for the Social Sciences, 21(01). [PDF](files/163-Full Paper-492-1-10-20180828.pdf)

Shamsinar Ibrahim, Hasyimah Razali, Masilah Mohamad, Siti Fairuza Hassam, & Kamarul Ariffin Mansor (2018). Assessing Passengers’ Satisfaction Towards The Northern Region Airlines Service Quality. Journal of Global Business and Social Entrepreneurship (GBSE). 4(10), 72 -86. [PDF](International Conference on Public Policy and Social Science 2010 (iCOPS).pdf)

Rahim, A., Kheng, L.K., Mansor, K.A., & Abas,N. (2017). The Antecedents Buying Intention of New Smartphone Among University Students. Advanced Science Letters, 23(11), 10538-10541. Indexing: Scopus. [WEB](https://www.ingentaconnect.com/content/asp/asl/2017/00000023/00000011/art00014)

Badri-Harun, A., Mansor, K.A., Shaari, Z.H., Zainol, M.R., & Amar, A. (2017). Factors Influencing Students of Technology-Based Universities to Become Entrepreneurs. International Review of Management and Marketing, 7(1), 319-325. Indexing: Scopus. [PDF](files/IRMM_2017(1)_319-325.pdf)

Mansor, K.A., & Ishak, W.I. (2015). Forecasting Tourist Arrivals to Langkawi Island Malaysia. Cross-Cultural Management Journal, 17(7), 69-76. Romanian Foundation for Business Intelligence (FRIA), Romania. (Published June 2015). Indexing: BDI http://cmj.bxb.ro/bdi/ and under evaluation period for ISI Web of Science Index. [PDF](CCMJ_Volume_XVII_Issue 1(2015).pdf)

Mansor, K.A., Masduki, R.M.N., Mohamad, M., Zulkarnain, N., & Aziz, N.A. (2015). A Study on Factors Influencing Muslim’s Consumers Preferences Towards Takaful Products In Malaysia. Romanian Statistical Review, 63(2), 78-89. Indexing: [ECSI Thompson Reuters and BDI](http://www.revistadestatistica.ro/index.php/indexing/) [PDF](RRS2_2015_A08.pdf)

### <i class="fab fa-readme"></i> Editorial Activities {.tabset}  

**EDITORS**  

Mansor, K.A., Ciprian, A. & Templ, M. (Eds), Vol. 49 No. 3 (2020) Special Issue iCMS2019, Austrian Journal of Statistics.  

Kor, L.-K., Ahmad, A.-R., Idrus, Z., Mansor, K.A. (Eds.), *Proceedings of the Third International Conference on Computing, Mathematics and Statistics (iCMS2017) - Transcending Boundaries, Embracing Multidisciplinary Diversities*  [Springer Link](https://www.springer.com/gp/book/9789811372780)  

Editorial Team - Independent Journal of Management & Production (IJM&P) E-ISSN: 2236-269X

Editorial Team – Austrian Journal of Statistics

Lee, K.L., Mansor, K.A., Nayan, A., Zakaria, S.F., & Idrus, Z. (2015). Quest for Research Excellence on Computing, Mathematics and Statistics.

***

**REVIEWERS**  

#### 2021  
Article Reviews - Melaka International Conference on Social Sciences, Science and Technology (MICSST) on the 30 - 31 March 2021 | Virtual Conference  

1. Training Effectiveness on The Knowledge, Attitude and Practices (KAP) Level of Good Hygiene Practices (GHP) Among Hawkers in Shah Alam, Selangor.  
2. Engagement in Daily Activities Among People Transitioning from Work to Retirement in Malaysian Perspective.  


#### 2020  
Article Reviews – The 5th National Academic Conference on “Sciences, Arts, and Research for Sustainable Development” and the 2nd International Academic Conference on "Roles of the university as the driver for changes and innovation-based society", held on the 13th – 14th February 2020 at the 2nd Floor, Rattanathepsatri Building, Thepsatri Rajabhat University, Thailand.  

1. The Study of Potential Tourism Resource for Tourist Development in Lopburi Province by Weerapol Noiklai, Payom Dhamabutra, Sahanon Pungbenchasirikul, Santidorn Pooripakdee.  
2. The management of Pung Thao Gong shrine (Ton Lumyai Market) knowledge understanding for the Chiang Mai Chinese and worshipers by Xin Liu, Charnnarong Srisuwan.  
3. Guideline development of Baba food PERANAKAN modernization in Phuket Province by Chalida Yamsrisuk.  
4. The product development and marketing promotion of woven straw ropes of the OTOP occupational group in Mueang district, Saraburi Province by Sopit Kamnuanchai, Kulchalee, Puangpejara Jumlong Khetjumnun, Panuphan Phermpiam, Ratchanok Suanseda, Saowanee Srikanjanarak.  
5. Perceptions of Entrepreneurs and Businesss Executives toward Entrepreneurship Education in Thai Universities by Rungluck Naksung.  
6. The Effect of Product Knowledge and Perceived Environmental Responsibility on Eco-Friendly Batik Purchase Delay Behavior by Ambar Lukitaningsih, Kusuma Chandra Kirana, Henny Welsa, Nonik Kusuma Ningrum.  
7. Learning Resources to Develop Students' Communicative Skills by Yuyun Yulia, Diyah Trinovita.  
8. Application of Tamansiswa teaching values through blended learning by Siti Mariah, Sri Wahyu Andayani.  
9. Climate Change Impacts on Water Resources in The Upper Chaophaya River Basin by Chaiwat Ekkawatpanit, Weerayuth Pratoomchai, Duangrudee Kositgittiwong.  
10. Attitudinal and Psychological Factors Affecting Perceived Value and Buying Intention for Fashion Garment in Myanmar Market by Thinn Thinn Aung, Kasemson Pipatsirisak.  
11. Development Guideline on Rice Supply Chain Management Skills for Farmers in Tha Wung District, Lop Buri Province by Chirawan somwang.  
12. A Primary Diagnosis of Supply Chain Performance for Community Enterprise: A Case Study of Fermented Fish chili Sauces by Moo 4 Woman Group (Hua Pa Chef), Hua Pa Sub-district, Phrom Buri District, Sing Buri Province by Chutima Thong-in, Jejira Pachayaka, Natpaphat Muangngam, Supalak Chitsiri, Usanee Jitimanee, Chirawan Somwang.  


#### 2019  
Article Review - "Visualization of association rules using R", The 4th International Conference on Computing, Mathematics and Statistics 2019 (iCMS2019)  

Article Review - "Modularity in Pass Network", The 4th International Conference on Computing, Mathematics and Statistics 2019 (iCMS2019)  

Abstract Review - "Detection of Business Cycle Turning Points in the Serbian Economic Activity", The 7th International Conference on New Challenges for Statistical Software: The use of R in Official Statistics (uRos2019)  

Abstract Review - "Utilization of big data for improving Consumption Trend Index: Estimation of the number of person per household based on the characteristic of purchase items", The 7th International Conference on New Challenges for Statistical Software: The use of R in Official Statistics (uRos2019)  

Abstract Review - "Implementation of the cell-key method based random noise approach in R", The 7th International Conference on New Challenges for Statistical Software: The use of R in Official Statistics (uRos2019)  


#### 2017
Article Review – “Job Satisfaction among Academic Staff: A Structural Equation Modeling Approach”, The 3rd International Conference on Computing, Mathematics and Statistics 2017 (iCMS2017) & The 5th Joint International Conference on New Challenges for Statistical Software: The Use of R in Official Statistics (UROS2017) – Asia Pacific.

Article Review - “Structural Equation Modelling Assessing Relationship Between Mathematics Beliefs, Teachers’ Attitudes And Teaching Practices Among Novice Teachers In Malaysia” for the Scopus-indexed AIP Conference Proceeding (International Conference on education, Mathematics and Science 2016 (ICEM 2016) in conjuction with 4th International Postgraduate Conference on Science and Mathematics 2016 (IPCSM 2016))

Article Review - “The Influence Of Psychosocial Learning Environment Toward Students’ Perceptions On Marzano Higher Order Thinking Skills” for the Scopus-indexed AIP Conference Proceeding (International Conference on education, Mathematics and Science 2016 (ICEM 2016) in conjuction with 4th International Postgraduate Conference on Science and Mathematics 2016 (IPCSM 2016))

#### 2016
Article Review - Study of the plywood panels properties using Geostatistic (IJM&P)

#### 2015
Editorial - Chapters in Book on Quest for Research Excellence on Computing, Mathematics and Statistics. The 2nd International Conference on Computing, Mathematics and Statistics (iCMS2015) – with LK Kor, KA Mansor, A Nayan, SF Zakaria, Z Idrus, 4.11.2015

Article Review – A comparative Study of the LWR-IM Traffic Model and Shockwave Analysis (2015 IEEE Conference on System, Process & Control)
Article Review – Modeling and Simulation of Electrical Resonance in EHV Transmission Line Case Study in West Java Region kV System (2015 IEEE Conference on System, Process & Control)

#### 2008
Article Review - Comparison Neural Networks Models for Short Term Forecasting of Natural Gas Consumption in Istanbul (First International Conference on the
Applications of Digital Information and Web Technologies (ICADIWT 2008), Co-Sponsored by IEEE, VSB- Technical University of Ostrava, Czech Republic, August 4 - 6 2008)

### <i class="fas fa-glasses"></i> Supervisions {.tabset}
Statistical Advisor & Industrial Training Supervisor

#### 2020  
*Analysis on Crime Data in Malaysia* by 2018635144 – Intan Nurfarhanis Binti Abdul Mutalib, 2019423558 – Mohamad Firdaus Bin Mohd Noor, 2019685716 - Nurasyikin Binti Abd Latif, 2019251862 – Mohamad Yusri Hakim Bin Mohamad Roslan, 2019422804 – Husnul Qatimah Adha Binti Mohamad Aznan.  

*Factors That Contribute to Abused Among Kids in Malaysia* by 2019255946 - Nurul Ain Binti Zamri, 2019402162 - Nur Fatin Aqilah Binti Marzuki, 2019806456 – Nur Fazariena Binti Che Othman.  

*Pandemic Covid 19Impact on Workers in Malaysia: A Case of Workers in Sungai Petani Kedah* by 2019274504 - Muhammad Zuhairy Bin Sukiman, 2019421452 -Syahrulaiman Fitri Bin Mohd Asri, 2019236696 - Muhammad Izzaddine Bin Izhar, 2019666744 – Ameerul Thaqiff Bin Suliman.  

*Dengue Cases* by 2020304881 - Arni Sofia Binti Abdullah, 2020705497 - Norfarahana Binti Zamri, 2020933177 - Norfarisha Binti Zulkifli.  

*Drunk Driving in Malaysia* by 2020166197 – Siti Fatimah Binti Mohd Sobri, 2020561707 - Siti Nuramirah Binti Meor Shamsuddin, 2020533365 - Nurnabilah Binti Ahmad Marzuki, 2020541819 - Siti Nurizzati Binti Nordin.  


#### 2017
Comparison Between Academic Staff And Non-Academic Staff On Relationship Of Mental Health And Quality Of Work Life In Uitm Kedah, Siti Shahidah Binti Md Saffar (2015208252)

The Knowledge, Attitude And Perception Of Negative Presenteesim Among Academic Staff At Uitm Kedah, Norazira Bintii Mohd Yusuf Sulaiman (2015872906)

Environmental Elements And Employees' Psychological Health: Are They Related? - A Case Study Of Astana Bayu City Group Sdn Bhd, Norhasikin Binti Moktar (2015830036)

#### 2016
The Factors That Influence The Non-Performing Loans (Npls) Among Private Staff In Penang, Norzubaidah Binti Abdul Aziz (2014926029) & Nur Insyirah Binti Mohd Zuki (2014190031)
Factors That Affect The Purchasing Decision On Motocycles Among Students In Uitm Kedah, Marsyasa Binti Basri

Factor Influencing Multinational Corporation To Invest In Penang, Mohd Nazimie Bin Mohd Hussain

Country Of Origin (Coo) Effect On Malaysia Consumers' Purchase Decisions Of Automobiles From Foreign 
Brands: In The Case Of UMK Pengkalan Chepa, Norshahirah Binti Suzilan

Factors That Influence The Intention To Purchase Halal Cosmetics Among Academic Staffs In Uitm Merbok, Nur Amira Nailah Binti Razamud-Din

#### 2015
Determinants Of Dependency Levels Towards Baitulmal In Seremban, Negeri Sembilan, Syaridatul Syadana Binti Esdaud (2012309987) & Siti Nurjihan Binti Marzuki (2013223858)

A Study On The Factors That Influence Retirement Saving Among Government Servants, Afa Husna Binti Md Radzi (2013771763) & Nur Izyani Binti Abdul Halim (2013822304)  


### <i class="fas fa-award"></i> Recognitions

**2020**  
Excellent Presentation Awards (“Integrating English Medium Mathematics Mobile Applications to Teach Low Achiever University Students”)  

> The 5th National Academic Conference on “Sciences, Arts, and Research for Sustainable Development” and the 2nd International Academic Conference on "Roles of the university as the driver for changes and innovation-based society", held on the 13th – 14th February 2020 at the 2nd Floor, Rattanathepsatri Building, Thepsatri Rajabhat University, Thailand.  

**2014**  
Bronze Medal (“Testing Mediation Effect in Social Science Research using Microsoft(R) Excel”)  

> Penang Invention, Innovation and Design 2014 (PIID 2014), 3 – 4 December 2014, Dewan Banquet UiTM Pulau Pinang, Malaysia.  

**2012**  
Bronze Medal (“Program Gambarajah Pokok Bayes”)  

> Innovation Platform 2012 (IP 2012), 2 – 4 November 2012, Village Mall Sungai Petani Kedah.  

**2012**  
Chairpersom Parallel Session  

> 1st International Conference on Decision Modeling 2012 (ICDeM 2012), 13 – 16 March 2012, Universiti Utara Malaysia (UUM) Sintok Kedah.  

**2011**  
Anugerah Perkhidmatan Cemerlang (UiTM Kedah)  
(Excellence Performance Award)  

**2004**  
Anugerah Perkhidmatan Cemerlang (UiTM Kedah)  
(Excellence Performance Award)
